### PR TITLE
add iRODSUser.comment and iRODSUser.info attributes

### PR DESCRIPTION
**Pull request by pigay**

### CODE REVIEW

**Comment by pigay** [comment]
info argument was missing too...

**Comment by trel** [comment]
looks good to me.   thanks!

i created #239 and will tweak these commit messages to point there.

you've got WIP in the title... is there anything else you want to add before I merge?

**Comment by d-w-moore** [comment]
Looks fine to me, too .  Will be testing a few other changes today, so I will throw this in alongside.

**Comment by pigay** [comment]
I'm done with WIP.

**Comment by trel** [comment]
Got it.

@d-w-moore let me know how the tests go, and I'll merge this.

**Comment by d-w-moore** [comment]
@pigay we'll merge this tomorrow with this diff applied to get all the tests back to passing. (only minor problems were encountered.)

```diff
From ac9cec2d14781c16af82ea322c999bff7b554242 Mon Sep 17 00:00:00 2001
From: d-w-moore <dmoore@renci.org>
Date: Thu, 10 Dec 2020 15:22:03 -0500
Subject: [PATCH] fix tests, iRODSUser info and comment attributes

one more thing in comment/info
---
 irods/test/admin_test.py |  4 ++--
 irods/user.py            | 19 +++++++++++++++++--
 2 files changed, 19 insertions(+), 4 deletions(-)

diff --git a/irods/test/admin_test.py b/irods/test/admin_test.py
index 74a2dad..1924c5f 100644
--- a/irods/test/admin_test.py
+++ b/irods/test/admin_test.py
@@ -361,7 +361,7 @@ class TestAdmin(unittest.TestCase):
         self.sess.users.create(self.new_user_name, self.new_user_type)
 
         # modify user comment
-        new_comment = '''comment-abc123!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~Z'''
+        new_comment = '''comment-abc123!"#$%&'()*+,-./:;<=>?@[\]^_{|}~Z''' # omitting backtick due to #170
         self.sess.users.modify(self.new_user_name, 'comment', new_comment)
 
         # check comment was modified
@@ -381,7 +381,7 @@ class TestAdmin(unittest.TestCase):
         self.sess.users.create(self.new_user_name, self.new_user_type)
 
         # modify user info
-        new_info = '''info-abc123!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~Z'''
+        new_info = '''info-abc123!"#$%&'()*+,-./:;<=>?@[\]^_{|}~Z''' # omitting backtick due to #170
         self.sess.users.modify(self.new_user_name, 'info', new_info)
 
         # check info was modified
diff --git a/irods/user.py b/irods/user.py
index d93150b..663f834 100644
--- a/irods/user.py
+++ b/irods/user.py
@@ -3,6 +3,7 @@ from irods.models import User, UserGroup, UserAuth
 from irods.meta import iRODSMetaCollection
 from irods.exception import NoResultFound
 
+_Not_Defined = ()
 
 class iRODSUser(object):
 
@@ -13,11 +14,25 @@ class iRODSUser(object):
             self.name = result[User.name]
             self.type = result[User.type]
             self.zone = result[User.zone]
-            self.comment = result[User.comment]
-            self.info = result[User.info]
+            self._comment = result.get(User.comment, _Not_Defined)  # - these not needed in results for object ident,
+            self._info = result.get(User.info, _Not_Defined)        #   so we fetch lazily via a property
         self._meta = None
 
     @property
+    def comment(self):
+        if self._comment == _Not_Defined:
+            query = self.manager.sess.query(User.id,User.comment).filter(User.id == self.id)
+            self._comment = query.one()[User.comment]
+        return self._comment
+
+    @property
+    def info(self):
+        if self._info == _Not_Defined:
+            query = self.manager.sess.query(User.id,User.info).filter(User.id == self.id)
+            self._info = query.one()[User.info]
+        return self._info
+
+    @property
     def dn(self):
         query = self.manager.sess.query(UserAuth.user_dn).filter(UserAuth.user_id == self.id)
         return [res[UserAuth.user_dn] for res in query]
-- 
2.7.4

```

**Pull request merged**
