### PR TITLE
[#567] Curb log output to stderr for (and after) pool_test

### PR DESCRIPTION
**Pull request by d-w-moore**
Fix the flood of XML being printed out from pool_test and any tests run on the same terminal thereafter within the same PRC suite run. Affected command : `cd <REPO>/irods/test ; python runner.py`

### CODE REVIEW

**Review by alanking — COMMENTED** [review]
Seems fine to me. I'm guessing all the tests pass and the output is now showing (or not, I suppose) as expected?

Pending any other review comments, I say we go ahead and squash to one (omit #).

**Review by korydraughn — COMMENTED** [review]
I second @alanking's comments.

**Comment by d-w-moore** [comment]
Ready for review...

**Review by alanking — APPROVED** [review]
Squash and # it

**Pull request merged**
