### PR TITLE
Get property comments from replica object

### PR DESCRIPTION
**Pull request by GwenLdR**
Expose the property "comments" as checksum or size for object replica

### CODE REVIEW

**Comment by d-w-moore** [comment]
Seems fine as long as comments is a per-replica field.  Do we have a test for it?

**Comment by d-w-moore** [comment]
I've verified it with a test, and created an issue for the new functionality. @GwenLdR , could you add the issue number at the start of your commit message?

**Comment by korydraughn** [comment]
@GwenLdR Please update your commit message to include the issue number like so.
```
[#450] Get property comments from replica object
```

**Comment by korydraughn** [comment]
@d-w-moore Please mark the PR as approved so we know you looked over it. Thanks.

**Review by korydraughn — APPROVED** [review]
Looks good to me.

**Review by alanking — APPROVED** [review]
I can fix up the commit message to link with #450. Will do that and merge pending @d-w-moore's approval.

**Comment by korydraughn** [comment]
Sounds good.

**Review by d-w-moore — APPROVED** [review]

**Comment by GwenLdR** [comment]
Oops, i didn't see yesterday your last comments.
So do I still have to do something?

**Comment by d-w-moore** [comment]
@GwenLdR I think we're ok with the commit as is; I've written the test already and approved the PR so @alanking should be able to affix the issue number for the merge.

**Comment by trel** [comment]
already merged.

**Comment by GwenLdR** [comment]
Thank you all !

**Pull request merged**
