### PR TITLE
Add force option to data_object_manager create following the other functions.

### PR DESCRIPTION
**Pull request by RubenGarcia**
Needed to overwrite files in iRODS.

### CODE REVIEW

**Comment by trel** [comment]
Thanks Ruben.   We'll need a test.

Was this not possible before, using `**options`?   Or is this just providing convenience and consistency?

**Comment by d-w-moore** [comment]
@RubenGarcia  - could you fill me in on the specific error and/or use case?

**Comment by RubenGarcia** [comment]
This is just providing convenience and consistency. 
But it is also motivated because I could not find documentation on the possible values of **options. Where are those documented?

**Comment by RubenGarcia** [comment]
Specific usecase: Create a file, overwriting if it already exists.
```
session = iRODSSession(...)
obj1 = session.data_objects.create('/LRZLexisZone/home/rods/a.txt') 
# succeeds
obj2 = session.data_objects.create('/LRZLexisZone/home/rods/a.txt') 
# fails with irods.exception.OVERWRITE_WITHOUT_FORCE_FLAG: None
obj3 = obj3 = session.data_objects.create('/LRZLexisZone/home/rods/a.txt', force=True)
# succeeds
```

**Comment by RubenGarcia** [comment]
Test file added.

**Comment by RubenGarcia** [comment]
I added a commit to document creation of users, to close
https://github.com/irods/python-irodsclient/issues/226

**Comment by d-w-moore** [comment]
@RubenGarcia , in regard to the available options for object/create, I think we'd have to "use the source" - On my machine, with 4.2.8 of iRODS checked out, I can do --
```
$ perl -ne 'print if /^int rsDataObjCreate/../^}/' ~/github/irods/server/api/src/rsDataObjCreate.cpp | grep  _KW
        addKeyVal( &dataObjInp->condInput, CROSS_ZONE_CREATE_KW, "" );
        rmKeyVal( &dataObjInp->condInput, CROSS_ZONE_CREATE_KW );
    // server in this zone for this operation.  if there is a RESC_HIER_STR_KW then
    char* resc_hier = getValByKey( &dataObjInp->condInput, RESC_HIER_STR_KW );
        addKeyVal( &dataObjInp->condInput, RESC_HIER_STR_KW, hier.c_str() );
    lockType = getValByKey( &dataObjInp->condInput, LOCK_TYPE_KW );
            rmKeyVal( &dataObjInp->condInput, LOCK_TYPE_KW );
    addKeyVal( &dataObjInp->condInput, SEL_OBJ_TYPE_KW, "dataObj" );
            addKeyVal( &dataObjInp->condInput, LOCK_FD_KW, fd_string );
            addKeyVal( &dataObjInp->condInput, LOCK_FD_KW, fd_string );
        /* rmKeyVal (&dataObjInp->condInput, FORCE_FLAG_KW); */
        addKeyVal(&dataObjInp->condInput, OPEN_TYPE_KW, std::to_string(CREATE_TYPE).c_str());
        /* rmKeyVal (&dataObjInp->condInput, FORCE_FLAG_KW); */
        if ( getValByKey( &dataObjInp->condInput, FORCE_FLAG_KW ) != NULL ) {
                    char* dst_resc_kw = getValByKey( &dataObjInp->condInput, DEST_RESC_NAME_KW );
            addKeyVal( &dataObjInp->condInput, RESC_HIER_STR_KW, hier.c_str() );
            addKeyVal( &dataObjInp->condInput, DEST_RESC_NAME_KW, top_resc.c_str() );
            addKeyVal(&dataObjInp->condInput, OPEN_TYPE_KW, std::to_string(OPEN_FOR_WRITE_TYPE).c_str());
            addKeyVal( &dataObjInp->condInput, LOCK_FD_KW, fd_string );
```
Of those, I'd say FORCE_FLAG_KW and CROSS_ZONE_CREATE_KW are probably the ones that the create operation respects. So you're right, those options needs to be passed in. I wasn't aware of the need for force on create until now : ) ! Will study it more closely.

**Comment by d-w-moore** [comment]
@RubenGarcia The change to the create( ) call looks good, I need to integrate the test properly and sent you a patch to apply on this branch before we  merge. Will have that to you later today.

**Comment by d-w-moore** [comment]
@RubenGarcia , here are my two patches . The first just generalizes the filename being created in the test; the second removes the setting of the file type. (Technically we can do this separately after creation of the data object, via `session.data_objects.modDataObjMeta` ... or automatically based on eg file extension, in the policy.

```diff
From d1127ab66def4de0bdd5d1890856fd4b9af2adb6 Mon Sep 17 00:00:00 2001
From: d-w-moore <dmoore@renci.org>
Date: Thu, 19 Nov 2020 10:15:33 -0500
Subject: [PATCH 1/2] generalize filename in force_create test

---
 irods/test/force_create.py | 3 +--
 1 file changed, 1 insertion(+), 2 deletions(-)

diff --git a/irods/test/force_create.py b/irods/test/force_create.py
index 306cf11..b373cfe 100644
--- a/irods/test/force_create.py
+++ b/irods/test/force_create.py
@@ -12,7 +12,6 @@ class TestForceCreate(unittest.TestCase):
     def setUp(self):
         self.sess = helpers.make_session()

-
     def tearDown(self):
         """Close connections."""
         self.sess.cleanup()
@@ -20,7 +19,7 @@ class TestForceCreate(unittest.TestCase):
     # This test should pass whether or not federation is configured:
     def test_force_create(self):
         session = self.sess
-        FILE = '/a.txt'
+        FILE = '/{session.zone}/home/{session.username}/a.txt'.format(**locals())
         try:
             session.data_objects.unlink(FILE)
         except:
-- 
2.7.4


From f12f711508532bfc28d62f59011f4d2fd9216a3f Mon Sep 17 00:00:00 2001
From: d-w-moore <dmoore@renci.org>
Date: Thu, 19 Nov 2020 10:19:56 -0500
Subject: [PATCH 2/2] prefer to set data types via modDataObjMeta

---
 irods/manager/data_object_manager.py | 1 -
 1 file changed, 1 deletion(-)

diff --git a/irods/manager/data_object_manager.py b/irods/manager/data_object_manager.py
index 3c5bf11..9898dce 100644
--- a/irods/manager/data_object_manager.py
+++ b/irods/manager/data_object_manager.py
@@ -82,7 +82,6 @@ class DataObjectManager(Manager):


     def create(self, path, resource=None, force=False, **options):
-        options[kw.DATA_TYPE_KW] = 'generic'

         if resource:
             options[kw.DEST_RESC_NAME_KW] = resource
-- 
2.7.4
```

**Comment by RubenGarcia** [comment]
I just saw this. Patch applied and pushed.

**Comment by d-w-moore** [comment]
Thanks @Ruben we'll merge soon.

**Comment by d-w-moore** [comment]
@RubenGarcia sorry for the delay in merging this, there's a lot going into the python client at the moment, and more  improvements we'll plan to embark on very soon. I plan on testing this and a number of other pulls today, then we'll get it in....

**Comment by trel** [comment]
closing this in favor of #242 (cannot force-push to forked branch).

commits still credit @RubenGarcia.

**Pull request closed without merging**
