### PR TITLE
minor README fix: XML_Parser_Type code sample

### PR DESCRIPTION
**Pull request by stsnel**

### CODE REVIEW

**Comment by korydraughn** [comment]
Thanks for this.

@d-w-moore Any thoughts?

**Comment by d-w-moore** [comment]
> Thanks for this.
> 
> @d-w-moore Any thoughts?

Seems good.  Mine was definitely a typo.

**Comment by d-w-moore** [comment]
Again, thanks, @stsnel

**Comment by alanking** [comment]
Shall we tag this with #5 and put it in?

**Comment by trel** [comment]
yes please

**Pull request merged**
