### PR TITLE
isue-386: initial change to add create and modify times for metadata

### PR DESCRIPTION
**Pull request by paulborgermans**

### CODE REVIEW

**Comment by d-w-moore** [comment]
This looks fine to me as is but I'd like to experiment with it a bit before giving a definitive review comment!

**Comment by trel** [comment]
I think we're going to look into an optional flag to return these two values along with the A,V,U itself.

**Comment by paulborgermans** [comment]
Yes, an optional flag is fine

**Comment by d-w-moore** [comment]
We should be able to implement the optional thing the same way we did with the "admin" flag

**Comment by korydraughn** [comment]
Excellent.

**Comment by d-w-moore** [comment]
@trel @korydraughn After more examination - I don't think the optional flag thing is really necessary.  But I'm willing to be convinced...

**Comment by trel** [comment]
@d-w-moore please demonstrate how to provide AVU timestamp information, but only upon request.

**Comment by d-w-moore** [comment]
with these existing commits  applied, we can do : 
```
>>> d = session.data_objects.get('/path/to/data')
>>> m = data_obj.metadata['someKey']
>>> m.create_time
datetime.datetime(2022, 9, 4, 21, 46, 35)
>>> m.modify_time
datetime.datetime(2022, 9, 4, 21, 46, 35)
```

**Comment by d-w-moore** [comment]
Not sure yet if create time and modify time are ever different.  One attempt at forcing them to be different has failed ....

**Comment by d-w-moore** [comment]
Ah. scratch previous comment; changing the AVU via d.metadata.set(...) will allow create and modify times to be different, likely because the set API is used. Whereas `iRODSMetaCollection.__setitem__` actually deletes AVU's and re-adds them behind the scenes....

**Comment by d-w-moore** [comment]
@trel did that demonstation, as it was, prove adequate? 

And was the rationale behind the optional  flag that we wouldn't waste space populating the attributes unless the optional flag  is given as `True` ? 

Just making sure I have the right sense of things.

**Comment by d-w-moore** [comment]
> provide AVU timestamp information, but only upon request.

@trel Did you mean, by retrieving timestamps as columns in the DB query only if the flag is True?

**Comment by korydraughn** [comment]
The idea of making those fields optional is so queries don't waste memory. In most cases, the create/modify times aren't needed. Always fetching those fields is wasteful. We want to give devs the option to request those fields when needed.

**Comment by trel** [comment]
Right - with the existing commit, we'd ALWAYS be sending the two timestamps with every retrieved AVU... and that could be a lot / unnecessary over time.

**Comment by d-w-moore** [comment]
OK, can certainly do that.  When the timestamps flag is not asserted, those fields within the AVU will then default to a None value.

**Comment by trel** [comment]
Right - I think that is what we're interested in seeing.

**Comment by alanking** [comment]
#390 will address the optional piece of this work and will not be merged until this is merged.

@paulborgermans - Can you change the commit to message to look like this?
```
[#386] initial change to add create and modify times for metadata
```
Then, we can merge this. Thanks!

**Review by d-w-moore — APPROVED** [review]

**Comment by d-w-moore** [comment]
Python client test suite passes for this PR....
Moving on then, my next test will be for #390 which fits atop this one  and I'll report those results on that page.

**Pull request merged**
