### PR TITLE
[550] Add support for client hints

### PR DESCRIPTION
**Pull request by stsnel**

### CODE REVIEW

**Review by alanking — COMMENTED** [review]
Looks good to me!

...I do have one question, though. Is the `irods.session` the right place for this? I don't use PRC enough to know of a better place, but just want to make sure we considered other designs (a new Model, a property of a `Connection`, etc.).

**Comment by stsnel** [comment]
> ...I do have one question, though. Is the `irods.session` the right place for this? I don't use PRC enough to know of a better place, but just want to make sure we considered other designs (a new Model, a property of a `Connection`, etc.).

Right, I chose `session.py` initially, since it already has the `server_version` attribute, and it seemed logical to me to put attributes that show information about the server in the same place. But I'm also happy to move it elsewhere if that fits the design better.

**Comment by trel** [comment]
Note - this is information from the connected server only.... right?

**Review by d-w-moore — APPROVED** [review]
This seems fine, and I guess it probably provides a good way to programmatically determine if e.g. a rule or microservice could be called on a particular session handle.  Good addition!

**Comment by alanking** [comment]
Sold. Merging. Thanks!

**Pull request merged**
