### PR TITLE
[#180] add the "in" genquery operator

### PR DESCRIPTION
**Pull request by d-w-moore**

### CODE REVIEW

**Comment by trel** [comment]
i like it - i see the test... can we get a couple examples in the README as well?

**Comment by d-w-moore** [comment]
Definintely. Examples for this and more will be added to the README.

**Comment by d-w-moore** [comment]
All tests passed and the codacy comments are not relevant (the variables are used).

**Comment by trel** [comment]
Gotcha - merging.    Will get your README stuff in the next PR.

**Pull request merged**
