### PR TITLE
Introductory explanation. mention the ~/.irods dir, needed when testing

### PR DESCRIPTION
**Pull request by d-w-moore**

### CODE REVIEW

**Comment by trel** [comment]
i think this can make it into 3.0.0 too.   please add #664 and # it.

**Review by alanking — APPROVED** [review]
Yes, please # (with commit message as suggested by @trel)

**Comment by d-w-moore** [comment]
> Yes, please # (with commit message as suggested by @trel)

will do

**Comment by d-w-moore** [comment]
Okay all that is done.

**Pull request merged**
