### PR TITLE
PRC test suite for 4-2-stable pre 4 2 9

### PR DESCRIPTION
**Pull request by d-w-moore**
Corrects all known issues with python-irodsclient tests failing due to changes in `4-2-stable` in **irods/irods** ...
adds a few features, too.
Ok, the client dot is included. 
Even more recently, if you can name it, it's in there.

### CODE REVIEW

**Comment by d-w-moore** [comment]
Corrects all known issues with python-irodsclient tests failing due to changes in `4-2-stable` in **irods/irods**

**Comment by trel** [comment]
last commit message should be "binbytebuf" -> "binbytesbuf"

**Comment by trel** [comment]
looks like a couple of these could be squashed together.     otherwise, i don't see anything problematic.

**Comment by d-w-moore** [comment]
Ok - will go ahead with the squash, comment correction and couple of CI tests. then will #

**Comment by trel** [comment]
yes please, another cycle of eyes before #ing.

**Comment by d-w-moore** [comment]
This seems ready for merge. Tested on Centos and all Ubuntus; Python2 and 3. Not #/squashing yet though, in case other eyes notice issues remaining.

**Comment by trel** [comment]
codacy has a couple things you probably want to look at (JSON_Message, etc.) - most you can safely ignore.

squash whenever is good - seems multiple 221's might go together?   your call.

don't # yet.

**Comment by d-w-moore** [comment]
The JSON_Message being flagged as not a part of the `irods.message` is weird, apparently codacy itself has some problems.
Remainder of codacy points do not seem critical. 
Not sure why the commits are now listed out-of-order since I squashed and force pushed....

Anyhow, now doing a final sanity test.

**Comment by trel** [comment]
if you're seeing them out of order on this github page, you may just need to hard refresh - the auto-updating sometimes leaves some extra bits around...

**Comment by trel** [comment]
i see one commit without an issue number, so annotate or squash it please.

**Comment by d-w-moore** [comment]
Done, and  sanity test passed.  time to # ?

**Comment by trel** [comment]
yes, please # em all!

**Comment by d-w-moore** [comment]
Done!

**Comment by trel** [comment]
we did it!    please close the relevant issues.

**Pull request merged**
