### PR TITLE
GSI authentication

### PR DESCRIPTION
**Pull request by pdonorio**
Solves #56

### CODE REVIEW

**Comment by adetorcy** [comment]
Thank you, this will be very useful.
Before your PR can be merged though all the [unit tests](https://github.com/irods/python-irodsclient/tree/master/irods/test) need to pass. 
Please review your changes. For example [these lines](https://github.com/pdonorio/python-irodsclient/commit/d671469d846ed8def5bb911340663cf529173035#diff-04ec672feca5e7a605db23f782783a98L367) should not be removed.

**Comment by pdonorio** [comment]
Oops, in recompressing the commits I wrongly deleted things.
I will fix this soon.

BTW how do you run your tests? Do I have a way (a docker image perhaps?) to make sure that if I run them I'm in the same position as you? Thanks

**Comment by pdonorio** [comment]
Ok, I brought back what was mistakenly erased.

To run all tests both on password credentials and GSI I had to use my docker configuration, see instructions [here](https://github.com/EUDAT-B2STAGE/docker-images/tree/master/usecases/irodsgsi).

I saved my config.py related, where I have 'rodminer' which is a user with both password and certificate, and with admin privileges on iCAT. You also need to export variables for certificates:
```
# volume with common certificates on icat and client in our docker compose
export X509_CERT_DIR="/opt/certificates/caauth"
export X509_USER_CERT="/opt/certificates/rodsminer/userkey.pem"
export X509_USER_KEY="/opt/certificates/rodsminer/usercert.pem"
```

And this is the result with running all tests:
```
Running tests...
----------------------------------------------------------------------
  test_list_acl (access_gsi_test.TestAccess) ... OK (0.357s)
  test_set_collection_acl (access_gsi_test.TestAccess) ... OK (0.245s)
  test_set_data_acl (access_gsi_test.TestAccess) ... OK (0.463s)
  test_list_acl (access_test.TestAccess) ... OK (0.256s)
  test_set_collection_acl (access_test.TestAccess) ... OK (0.134s)
  test_set_data_acl (access_test.TestAccess) ... OK (0.252s)
  test_create_delete_local_user (admin_test.TestAdmin) ... OK (0.142s)
  test_create_delete_user_zone (admin_test.TestAdmin) ... OK (0.118s)
  test_make_compound_resource (admin_test.TestAdmin) ... OK (0.846s)
  test_make_ufs_resource (admin_test.TestAdmin) ... OK (0.337s)
  test_modify_user_type (admin_test.TestAdmin) ... OK (0.143s)
  test_modify_user_type_with_zone (admin_test.TestAdmin) ... OK (0.111s)
  test_resource_context_string (admin_test.TestAdmin) ... OK (0.227s)
  test_session_with_client_user (admin_test.TestAdmin) ... OK (0.001s)
  test_set_user_password (admin_test.TestAdmin) ... OK (0.110s)
  test_append_to_collection (collection_gsi_test.TestCollection)
Append a new file to the collection ... OK (0.223s)
  test_collection_metadata (collection_gsi_test.TestCollection) ... OK (0.242s)
  test_get_collection (collection_gsi_test.TestCollection) ... OK (0.283s)
  test_move_coll_to_coll (collection_gsi_test.TestCollection) ... OK (0.387s)
  test_remove_deep_collection (collection_gsi_test.TestCollection) ... OK (3.589s)
  test_remove_from_collection (collection_gsi_test.TestCollection)
Delete a file from a collection ... OK (0.212s)
  test_rename_collection (collection_gsi_test.TestCollection) ... OK (0.274s)
  test_repr_coll (collection_gsi_test.TestCollection) ... OK (0.214s)
  test_update_in_collection (collection_gsi_test.TestCollection)
Modify a file in a collection ... OK (0.206s)
  test_walk_collection (collection_gsi_test.TestCollection) ... OK (7.276s)
  test_walk_collection_topdown (collection_gsi_test.TestCollection) ... OK (7.512s)
  test_append_to_collection (collection_test.TestCollection)
Append a new file to the collection ... OK (0.091s)
  test_collection_metadata (collection_test.TestCollection) ... OK (0.100s)
  test_get_collection (collection_test.TestCollection) ... OK (0.111s)
  test_move_coll_to_coll (collection_test.TestCollection) ... OK (0.221s)
  test_remove_deep_collection (collection_test.TestCollection) ... OK (3.456s)
  test_remove_from_collection (collection_test.TestCollection)
Delete a file from a collection ... OK (0.092s)
  test_rename_collection (collection_test.TestCollection) ... OK (0.167s)
  test_repr_coll (collection_test.TestCollection) ... OK (0.101s)
  test_update_in_collection (collection_test.TestCollection)
Modify a file in a collection ... OK (0.093s)
  test_walk_collection (collection_test.TestCollection) ... OK (7.853s)
  test_walk_collection_topdown (collection_test.TestCollection) ... OK (9.110s)
  test_connection (connection_gsi_test.TestConnections) ... OK (0.183s)
  test_connection_destructor (connection_gsi_test.TestConnections) ... OK (0.159s)
  test_failed_connection (connection_gsi_test.TestConnections) ... OK (0.003s)
  test_reply_failure (connection_gsi_test.TestConnections) ... OK (0.161s)
  test_send_failure (connection_gsi_test.TestConnections) ... 2017-01-09 14:47:58,696 irods.connection-ERROR [/code/myfork/irods/connection.py 61] Unable to send message. Connection to remote host may have closed. Releasing connection from pool.
OK (0.163s)
  test_connection (connection_test.TestConnections) ... OK (0.057s)
  test_connection_destructor (connection_test.TestConnections) ... OK (0.057s)
  test_failed_connection (connection_test.TestConnections) ... OK (0.002s)
  test_reply_failure (connection_test.TestConnections) ... OK (0.062s)
  test_send_failure (connection_test.TestConnections) ... 2017-01-09 14:47:58,934 irods.connection-ERROR [/code/myfork/irods/connection.py 61] Unable to send message. Connection to remote host may have closed. Releasing connection from pool.
OK (0.055s)
  test_create_with_checksum (data_obj_gsi_test.TestDataObjOps) ... SKIP (0.000s)
  test_force_unlink (data_obj_gsi_test.TestDataObjOps) ... OK (0.349s)
  test_invalid_get (data_obj_gsi_test.TestDataObjOps) ... OK (0.226s)
  test_move_obj_to_coll (data_obj_gsi_test.TestDataObjOps) ... OK (0.389s)
  test_multiple_reads (data_obj_gsi_test.TestDataObjOps) ... OK (0.610s)
  test_obj_replicate (data_obj_gsi_test.TestDataObjOps) ... OK (0.774s)
  test_obj_truncate (data_obj_gsi_test.TestDataObjOps) ... OK (0.385s)
  test_rename_obj (data_obj_gsi_test.TestDataObjOps) ... OK (0.380s)
  test_create_with_checksum (data_obj_test.TestDataObjOps) ... SKIP (0.001s)
  test_force_unlink (data_obj_test.TestDataObjOps) ... OK (0.207s)
  test_invalid_get (data_obj_test.TestDataObjOps) ... OK (0.104s)
  test_move_obj_to_coll (data_obj_test.TestDataObjOps) ... OK (0.292s)
  test_multiple_reads (data_obj_test.TestDataObjOps) ... OK (0.478s)
  test_obj_replicate (data_obj_test.TestDataObjOps) ... OK (0.406s)
  test_obj_truncate (data_obj_test.TestDataObjOps) ... OK (0.248s)
  test_rename_obj (data_obj_test.TestDataObjOps) ... OK (0.278s)
  test_files_generator (extended_gsi_test.TestContinueQuery) ... OK (236.219s)
  test_query_offset_limit_all (extended_gsi_test.TestContinueQuery) ... OK (235.172s)
  test_walk_large_collection (extended_gsi_test.TestContinueQuery) ...
OK (236.408s)
test_files_generator (extended_test.TestContinueQuery) ... OK (233.715s)
  test_query_offset_limit_all (extended_test.TestContinueQuery) ... OK (250.658s)
  test_walk_large_collection (extended_test.TestContinueQuery) ... OK (243.855s)
  test_file_get (file_gsi_test.TestFiles) ... OK (0.315s)
  test_file_open (file_gsi_test.TestFiles) ... OK (0.318s)
  test_file_read (file_gsi_test.TestFiles) ... OK (0.335s)
  test_file_write (file_gsi_test.TestFiles) ... OK (0.350s)
  test_file_get (file_test.TestFiles) ... OK (0.214s)
  test_file_open (file_test.TestFiles) ... OK (0.223s)
  test_file_read (file_test.TestFiles) ... OK (0.236s)
  test_file_write (file_test.TestFiles) ... OK (0.215s)
  test_auth_response (message_test.TestMessages) ... OK (0.001s)
  test_gen_query_inp (message_test.TestMessages) ... OK (0.004s)
  test_gen_query_out (message_test.TestMessages) ... OK (0.005s)
  test_inx_ival_pair (message_test.TestMessages) ... OK (0.001s)
  test_key_val_pair (message_test.TestMessages) ... OK (0.000s)
  test_sql_result (message_test.TestMessages) ... OK (0.001s)
  test_startup_pack (message_test.TestMessages) ... OK (0.001s)
  test_add_coll_meta (meta_gsi_test.TestMeta) ... OK (0.311s)
  test_add_obj_meta (meta_gsi_test.TestMeta) ... OK (0.315s)
  test_add_obj_meta_empty (meta_gsi_test.TestMeta)
Should raise exception ... OK (0.270s)
  test_copy_obj_meta (meta_gsi_test.TestMeta) ... OK (0.399s)
  test_get_obj_meta (meta_gsi_test.TestMeta) ... OK (0.292s)
  test_irodsmetacollection_data_obj (meta_gsi_test.TestMeta) ... OK (0.627s)
  test_meta_repr (meta_gsi_test.TestMeta) ... OK (0.387s)
  test_remove_obj_meta (meta_gsi_test.TestMeta) ... OK (0.313s)
  test_add_coll_meta (meta_test.TestMeta) ... OK (0.178s)
  test_add_obj_meta (meta_test.TestMeta) ... OK (0.190s)
  test_add_obj_meta_empty (meta_test.TestMeta)
Should raise exception ... OK (0.158s)
  test_copy_obj_meta (meta_test.TestMeta) ... OK (0.232s)
  test_get_obj_meta (meta_test.TestMeta) ... OK (0.155s)
  test_irodsmetacollection_data_obj (meta_test.TestMeta) ... OK (0.473s)
  test_meta_repr (meta_test.TestMeta) ... OK (0.295s)
  test_remove_obj_meta (meta_test.TestMeta) ... OK (0.184s)
  test_destroy_active (pool_gsi_test.TestPool) ... OK (0.174s)
  test_destroy_idle (pool_gsi_test.TestPool) ... OK (0.169s)
  test_release_connection (pool_gsi_test.TestPool) ... OK (0.170s)
  test_release_disconnected (pool_gsi_test.TestPool) ... 2017-01-09 15:12:07,783 irods.connection-ERROR [/code/myfork/irods/connection.py 61] Unable to send message. Connection to remote host may have closed. Releasing connection from pool.
OK (0.158s)
  test_destroy_active (pool_test.TestPool) ... OK (0.054s)
  test_destroy_idle (pool_test.TestPool) ... OK (0.063s)
  test_release_connection (pool_test.TestPool) ... OK (0.054s)
  test_release_disconnected (pool_test.TestPool) ... 2017-01-09 15:12:08,023 irods.connection-ERROR [/code/myfork/irods/connection.py 61] Unable to send message. Connection to remote host may have closed. Releasing connection from pool.
OK (0.068s)
  test_collections_query (query_gsi_test.TestQuery) ... OK (0.306s)
  test_files_query (query_gsi_test.TestQuery) ... OK (0.273s)
  test_query_first (query_gsi_test.TestQuery) ... OK (0.297s)
  test_query_like (query_gsi_test.TestQuery)
Equivalent to: ... OK (0.309s)
  test_query_one (query_gsi_test.TestQuery) ... OK (0.272s)
  test_query_order_by (query_gsi_test.TestQuery) ... OK (0.306s)
  test_query_order_by_desc (query_gsi_test.TestQuery) ... OK (0.263s)
  test_query_order_by_invalid_param (query_gsi_test.TestQuery) ... OK (0.286s)
  test_query_strip (query_gsi_test.TestQuery) ... OK (0.265s)
  test_query_wrong_type (query_gsi_test.TestQuery) ... OK (0.287s)
  test_resources_query (query_gsi_test.TestQuery)
Lists resources ... OK (0.283s)
  test_users_query (query_gsi_test.TestQuery)
Lists all users and look for known usernames ... OK (0.282s)
  test_collections_query (query_test.TestQuery) ... OK (0.194s)
  test_files_query (query_test.TestQuery) ... OK (0.151s)
  test_query_first (query_test.TestQuery) ... OK (0.176s)
  test_query_like (query_test.TestQuery)
Equivalent to: ... OK (0.164s)
  test_query_one (query_test.TestQuery) ... OK (0.159s)
  test_query_order_by (query_test.TestQuery) ... OK (0.150s)
  test_query_order_by_desc (query_test.TestQuery) ... OK (0.167s)
  test_query_order_by_invalid_param (query_test.TestQuery) ... OK (0.143s)
  test_query_strip (query_test.TestQuery) ... OK (0.154s)
  test_query_wrong_type (query_test.TestQuery) ... OK (0.167s)
  test_resources_query (query_test.TestQuery)
Lists resources ... OK (0.160s)
  test_users_query (query_test.TestQuery)
Lists all users and look for known usernames ... OK (0.177s)
  test_add_metadata_from_rule (rule_test.TestRule) ... OK (0.228s)
  test_add_metadata_from_rule_file (rule_test.TestRule) ... OK (0.239s)
  test_retrieve_std_streams_from_rule (rule_test.TestRule) ... OK (0.059s)
  test_files (unicode_gsi_test.TestUnicodeNames) ... OK (22.514s)
  test_files (unicode_test.TestUnicodeNames) ... OK (22.963s)
  test_add_users_to_group (user_group_gsi_test.TestUserGroup) ... OK (1.366s)
  test_create_group (user_group_gsi_test.TestUserGroup) ... OK (0.223s)
  test_add_users_to_group (user_group_test.TestUserGroup) ... OK (1.258s)
  test_create_group (user_group_test.TestUserGroup) ... OK (0.120s)

----------------------------------------------------------------------
Ran 141 tests in 1549.963s

OK (skipped=2)

Generating XML reports...
```

*Notes*:
- We duplicated all tests file for making the gsi version, I don't know if you're happy with that.
- It would be much better to define together a way to make possible tests on GSI also for other users
- TestContinueQuery is very slow (~10min), can't it be smaller? 
- I still see that error on server side even if commands with GSI work fine:

```
Jan  9 14:43:30 pid:285 ERROR: [-]	iRODS/server/core/src/rsApiHandler.cpp:520:readAndProcClientMsg :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message []
	[-]	iRODS/lib/core/src/sockComm.cpp:199:readMsgHeader :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']
		[-]	libtcp.cpp:197:tcp_read_msg_header :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [only read [0] of [4]]
```

**Comment by pdonorio** [comment]
Updated to fix a conflict. Any news?

**Comment by adetorcy** [comment]
I would like to make some edits before merging the PR. Can you please confirm that I can push to your repo? See item 4 on this page (checkbox 'allow edits from maintainers'): https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by pdonorio** [comment]
That item is already checked. Do I have to add you also as a collaborator?

**Comment by adetorcy** [comment]
That should not be necessary since your repo is a fork of my repo. But we'll see...

**Comment by adetorcy** [comment]
FYI you might want to do `git reset --hard origin/master` in your local master branch as I have changed the history

**Comment by adetorcy** [comment]
More changes coming...

**Comment by pdonorio** [comment]
Thanks for refactoring the tests and merging this code!

**Pull request merged**
