### PR TITLE
[510] update README to reflect removal of session.permissions

### PR DESCRIPTION
**Pull request by trel**
just the README portion, no code changes

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Looks fine. I take it the code still needs to be removed?

**Comment by trel** [comment]
correct

**Comment by korydraughn** [comment]
Is that planned for another PR will it be included in this one?

**Comment by trel** [comment]
I expect @d-w-moore will do the actual code removal - and probably as a separate PR.

Once the new one is ready, we can merge both at about the same time.

**Review by alanking — COMMENTED** [review]
I'm torn on this...

On the one hand, I'd almost rather see this removed entirely from the docs and mention the removal in the release notes so developers know to stop using it.

On the other hand, it would be helpful for developers to know *how* to make the jump from one to the other. Would a deprecations/removals/1.x transition section be helpful? Might be hard to make that comprehensive...

**Comment by trel** [comment]
right - i thought about just removing the entire paragraph/discussion... but maybe that goes away for 3.0.0?

**Comment by alanking** [comment]
Sure, seems good

**Comment by d-w-moore** [comment]
> I expect @d-w-moore will do the actual code removal - and probably as a separate PR.
> 
> Once the new one is ready, we can merge both at about the same time.

Yes, separate PR, I think.

**Comment by korydraughn** [comment]
Sounds good.

**Comment by trel** [comment]
i've added # - awaiting sibling PR before merging both.

**Pull request merged**
