### PR TITLE
[#148] DataObjectManager.put() should return reference to new object

### PR DESCRIPTION
**Pull request by jonlandrum**
[irods#148] DataObjectManager.put() should return reference to new object

### CODE REVIEW

**Comment by trel** [comment]
The commit message on this commit is referring to the other PR.

Please update it, reference the original issue, and we'll get it merged.

**Comment by trel** [comment]
I pushed a commit message update - thanks!

**Comment by jonlandrum** [comment]
> 
> 
> I pushed a commit message update - thanks!

Ah dammit, I'm sorry, I didn't realize you meant the commit message, even though that's exactly what you said. For some reason I thought you meant the comment on the PR. >_< Need more coffee.

**Comment by trel** [comment]
all good.

**Pull request merged**
