### PR TITLE
Replica comments test

### PR DESCRIPTION
**Pull request by d-w-moore**
The commit within this PR contains a test for the functionality provided in https://github.com/irods/python-irodsclient/pull/449

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Test looks good.

Will approve once the other PR is merged and this one is rebased on top of it.

**Comment by alanking** [comment]
#449 has been merged. Let's rebase and squash. Leave off #s and we'll have one last look. Also, please resolve open conversations

**Comment by d-w-moore** [comment]
Done

**Review by alanking — APPROVED** [review]

**Comment by d-w-moore** [comment]
A final test, then will add pound.

**Pull request merged**
