### PR TITLE
[#664] Update changelog

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Comment by trel** [comment]
will tweak to add some 'testing' issues...

but... where do you think they best fit?   the Changed section?   or Added because the tests were added...?

**Comment by korydraughn** [comment]
I left those out because the changelog highlights notable changes _(mentioned at the top of the document)_ and changes to tests don't apply to admins/users necessarily.

The tests are assumed to be part of the software improvement process, so no point in mentioning them IMO. Had there been some significant change related to testing that applied to the admins/users, only then would it be worth including words about them. Also, trying to figure out where to put words about testing wasn't obvious.

**Comment by trel** [comment]
okay - that's good.   just saw commits/issues that were not mentioned.   i defer to the plan.

**Comment by trel** [comment]
please #

**Comment by korydraughn** [comment]
Pounded.

**Pull request merged**
