### PR TITLE
Added method to ResourceManager class allowing a user to query the da…

### PR DESCRIPTION
**Pull request by Fennersteel**
…ta resource for a specific attribute and have that be returned as a string.

### CODE REVIEW

**Comment by trel** [comment]
Thanks!   Can you add a test that exercises this new method?

**Comment by Fennersteel** [comment]
WIll do! Could you give me some direction on where and how to do this? I'm
still kind of new to the dev scene.

**Comment by trel** [comment]
Ah, no worries.

Can you at least share an example of how you are using / will use this in your own code?   What is the use case to add this method?

**Comment by Fennersteel** [comment]
Hello! Sorry for my late reply. I'm a student of the University of Arizona
working as an Applications Developer for CyVerse. I'm writing python
Ansible modules to help automate some of our administrative tasks, and
adding a method that will allow me to get an attribute of an irods resource
and return it as a string would be very helpful. The current module I'm
writing serves to iterate through a data resource and all of its parent
resources and set their status to "up". I'll include the module file as an
attachment.

**Comment by trel** [comment]
Can you add it to a code block in the github comment directly?   Thanks!

**Comment by Fennersteel** [comment]
Done!

**Comment by trel** [comment]
duplicated here for safe keeping...

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import ssl
import traceback
from ansible.module_utils.basic import AnsibleModule
from irods.session import iRODSSession

DOCUMENTATION = '''
---
module: irods_resource_up

short_description: Change status of resource and parents to "up"

version added: "2.11.11"

description: An ansible module for changing the status of a resource and
all of its parents to up.

options:
    resource:
        description:
            - the resource to modify
        required: true
        type: object

requirements:
    - python-irodsclient>=0.8.2

author:
    - Fenn Garnett (@Fennersteel)
'''

EXAMPLE = '''
# Set iRODS resource status to "up"
- name: Set status to "up"
    irods_resource_up:
        resource: ingestRes
        host: cyverse.org
        port: 1247
        admin_user: rods
        admin_password: 1234
        zone: tempZone
'''

RETURN = '''
exc:
    description:
        - type of last iRODS exception thrown
        - empty string when none is thrown
    type: str
    returned: always
exc_msg:
    description:
        - message of the last iRODS exception thrown
        - empty string when none is thrown
    type: str
    returned: always
'''


class IRODSResourceUpModule:
    """
    Module class
    """

    def __init__(self):
        """
        Initialize module
        """

        self.module_args = dict(
            resource=dict(type="str", required=True),
            host=dict(type="str", required=True),
            port=dict(type="int", required=True),
            admin_user=dict(type="str", no_log=True, required=True),
            admin_password=dict(type="str", no_log=True, required=True),
            zone=dict(type="str", required=True)
        )

        self.result = dict(
            changed=False,
            exit_msg='',
            exc='',
            exc_msg='',
        )

        self.module = AnsibleModule(
            argument_spec=self.module_args,
            supports_check_mode=True
        )

        self.ssl_context = ssl.create_default_context(
            purpose=ssl.Purpose.SERVER_AUTH, cafile=None, capath=None,
            cadata=None)

        self.ssl_settings = {"ssl_context": self.ssl_context}

        self.session = None

    def _init_session(self):
        try:
            self.session = iRODSSession(
                resource=self.module.params["resource"],
                host=self.module.params["host"],
                port=self.module.params["port"],
                user=self.module.params["admin_user"],
                password=self.module.params["admin_password"],
                zone=self.module.params["zone"],
                **self.ssl_settings)
        except Exception as exc:  # pylint: disable=broad-except
            self.result["exc"] = exc
            self.result["exc_message"] = "Unable to connect to iRODS."
            self._fail(self.result["exc_message"])

    def run(self):
        """
        Entry point for module class, method to be called to run the module
        """
        if self.module.check_mode:
            self.result["exit_msg"] = ""
            self.module.exit_json(**self.result)

        self._init_session()

        try:
            self._resource_up_recurse(self.module.params["resource"])
            self.module.exit_json(**self.result)
        except Exception as exc:  # pylint: disable=broad-except
            self.result["exc"] = type(exc).__name__
            self.result["exc_msg"] = traceback.format_exc()
            self._fail("Unable to set status of resource to 'up'")

    def _resource_up(self, resc):
        current_status = self.session.resources.get(resc)
        if current_status != "up":
            self.session.resources.modify(resc, "status", "up")
            self.result["changed"] = True

    def _resource_up_recurse(self, resc):
        self._resource_up(resc)
        next_resc = self.session.resources.get(resc, "parent")

        if next_resc:
            self._resource_up_recurse(next_resc)

    def _fail(self, msg, err=None):
        if self.session:
            self.session.cleanup()

        if err:
            self.module.fail_json(msg=msg + "\n" + str(err), **self.result)
        else:
            self.module.fail_json(msg=msg, **self.result)


def main():
    """
    Entrypoint of Ansible module
    """
    module = IRODSResourceUpModule()
    module.run()


if __name__ == '__main__':
    main()
```

So...

I see

```
        current_status = self.session.resources.get(resc)
```
and
```
        next_resc = self.session.resources.get(resc, "parent")
```
but neither of these call your new method `get_attribute()` that's in the proposed pull request.

I don't think you need any edits to this client library to do what you want...

You can get the parent of any resource with just `resc.parent`, then modify the status directly with
```
            self.session.resources.modify(resc, "status", "up")
```

**Comment by Fennersteel** [comment]
Hello! I realized that I was focusing on the wrong issue with the module. The modify function works as intended, you were correct. I need to be able to get the current status of an irods resource as a string, so I can check if an irods resource is or is not already set to "up" before running a status change. I pushed a new change to resource.py

**Comment by trel** [comment]
Ah, I see.   Yes, this is very clean.

**Comment by trel** [comment]
If you know how to squash your commits, please squash to a single commit and reference the issue in your commit message like...

"[ 384] your message here"

You can force push your updates and this PR will update automatically.

Once it's approved/perfect, we'll ask you to add a # in front of the number (and re-force-push) and we'll merge the PR.

**Comment by trel** [comment]
I was able to get the status (as a string) of a resource by name without any changes to this library...

```
    r = session.resources.get('demoResc')
    print(r.status)
```
or even shorter...
```
    print(session.resources.get('demoResc').status)
```

**Comment by Fennersteel** [comment]
Hey! My supervisor and I got the module working, thank you so much for your
input.

**Comment by trel** [comment]
Perfect - glad it's working.

**Pull request closed without merging**
