### PR TITLE
Patch tests to run for Python2 and Python >= 3.11

### PR DESCRIPTION
**Pull request by d-w-moore**

### CODE REVIEW

**Comment by SwooshyCueb** [comment]
Why are we adding Python 2 support?

**Comment by alanking** [comment]
> Why are we adding Python 2 support?

I believe the current directive is to support 2 and 3 (where possible) until 3.0.0 at which time support for 2 will be removed.

**Review by korydraughn — COMMENTED** [review]
I don't see anything unusual.

Do the tests pass?

**Review by alanking — DISMISSED** [review]
Looks good to me

**Comment by d-w-moore** [comment]
> I don't see anything unusual.
> 
> Do the tests pass?

checking that today.  Got to include solution to #565 also...

**Review by alanking — COMMENTED** [review]
New change seems fine. Please confirm / deny that tests are passing.

**Review by korydraughn — COMMENTED** [review]
Changes look good.

You have an extra space preceding 3.8 in the commit body. From your current commit message.
```
[_587] unique_name now hashes the call tuple for a random seed.
This will allow tests that depend on irods.test.helpers.unique_name
to run in Python3.11+.

The aforementioned hashing was internally and noiselessly performed
in Python  3.8 and before, but was deprecated in 3.9 and then
discontinued in 3.11.

As a result, we'll now perform it ourselves.
```

**Comment by korydraughn** [comment]
Latest changes look good. What's the status of this?

**Comment by d-w-moore** [comment]
> Latest changes look good. What's the status of this?

Will run the full suite and get back to you on it ! : )

**Comment by d-w-moore** [comment]
Tests passed.

**Review by alanking — APPROVED** [review]
\# it

**Pull request merged**
