### PR TITLE
[irods#404] Fix password_obfuscation in Windows (main)

### PR DESCRIPTION
**Pull request by korydraughn**
Rebased work from #405 on top of main.

### CODE REVIEW

**Comment by korydraughn** [comment]
That seems to be answered by this thread https://github.com/irods/python-irodsclient/pull/405#discussion_r998636343.

@d-w-moore @jpmcfarland

**Comment by trel** [comment]
oh right, saw that - but forgot.   carry on.

**Comment by korydraughn** [comment]
Are we happy with merging this PR?

@trel @jpmcfarland

**Comment by jpmcfarland** [comment]
I certainly am.  Thanks for the help!

**Comment by korydraughn** [comment]
No problem at all. Happy to help.

**Review by alanking — APPROVED** [review]
Would like one more eyeball from @d-w-moore to make sure we got everything but it looks to me like we did

**Review by d-w-moore — APPROVED** [review]
Looks good.

**Comment by korydraughn** [comment]
The original PR for this work has been cleaned up.

Closing this PR in favor of the original.

**Pull request closed without merging**
