### PR TITLE
[irods/irods_capability_automated_ingest 136] fix redundant disconnect

### PR DESCRIPTION
**Pull request by d-w-moore**

### CODE REVIEW

**Comment by d-w-moore** [comment]
regarding [irods/irods_capability_automated_ingest#136]

**Comment by d-w-moore** [comment]
The python client test suite has been run to test the integrity of this change.

**Comment by trel** [comment]
Please update the commit message to reference both [#241] and [irods/irods_capability_automated_ingest#136]

**Comment by trel** [comment]
And codacy has one tiny opinion.

**Comment by d-w-moore** [comment]
@trel - done.

**Comment by d-w-moore** [comment]
I know why codacy cares about the _disconnected attribute not being mentioned in the constructor, but in this case, we probably don't need to.  The only place it's read-accessed, it is given a default if it doesn't yet exist.

**Comment by d-w-moore** [comment]
I could place an initialization of 'self._disconnected = False' in `Connection.__init__` and it would be harmless enough.

**Comment by trel** [comment]
yes, please initialize to False.

**Pull request merged**
