### PR TITLE
[_660] do not run logging.basicConfig from library code.

### PR DESCRIPTION
**Pull request by d-w-moore**

### CODE REVIEW

**Review by korydraughn — APPROVED** [review]
Pound it.

**Review by alanking — COMMENTED** [review]
Just for my own understanding... The effect of this, according to #660, is that configuring the global logger in the client application will also affect the logging configuration for PRC. Is that right?

**Comment by d-w-moore** [comment]
> Just for my own understanding... The effect of this, according to #660, is that configuring the global logger in the client application will also affect the logging configuration for PRC. Is that right?

Yes, the logger hierarchy is a singleton tree structure particular to the Python ecosystem and the process hosting it.  It can be initialized once within the interpreter that calls basicConfig(... ) wherever that may happen.  Where that call initiates from is not important in terms of effect.  It's just that the main program is more likely to "know" how the application "prefers" to handle logging.

**Comment by d-w-moore** [comment]
@korydraughn - pounded.

**Pull request merged**
