### PR TITLE
[#576] Add missing admin_mode for metadata.apply_atomic_operations

### PR DESCRIPTION
**Pull request by paulborgermans**
See also issue #576

### CODE REVIEW

**Review by korydraughn — APPROVED** [review]
Thanks for the PR.

Looks good upon inspection.

Let's get another approval before merging.

**Review by alanking — COMMENTED** [review]
I think the change looks good. Either as part of this PR or a separate one, I think we should consider adding a test. Thoughts?

**Comment by korydraughn** [comment]
I agree. Should be trivial to add.

**Review by alanking — APPROVED** [review]
Okay. Let's go ahead and put this one in and we can handle adding a test before closing the issue.

**Comment by d-w-moore** [comment]
Thanks @paulborgermans . Test is now written and [underway to be merged](https://github.com/irods/python-irodsclient/pull/579).

**Pull request merged**
