### PR TITLE
[509,484] Update version mentioned in README for Quota

### PR DESCRIPTION
**Pull request by trel**

### CODE REVIEW

**Review by korydraughn — APPROVED** [review]
Looks good.

Pound when ready.

**Review by alanking — APPROVED** [review]
Unless there's a good reason for it, would prefer 484 to precede 509 in the commit title for ordered-ness. :)

**Comment by trel** [comment]
ah, fair.  will do.

**Review by alanking — APPROVED** [review]
Yep, let's # it.

**Comment by trel** [comment]
done - #'d.

**Pull request merged**
