### PR TITLE
miscsvrinfo class

### PR DESCRIPTION
**Pull request by bascibaran**
Implemented a class that corresponds to the icommand imiscsvrinfo. 
You can create an instance like
`m = miscsvrinfo(host,port) # port's default value is 1247`

upon initialization the class makes an API request and parses the reply to populate its attributes, which can then be accessed like so:
```
m.serverType
m.relVersion
m.apiVersion
m.rodsZone
m.uptime

```
`m.update(): method that sends an API request to refresh its attributes with current information. 
`
if you print m, you will get the same stdout output as running imiscsvrinfo.

### CODE REVIEW

**Comment by adetorcy** [comment]
Thank you very much for your contribution. Please address the following items before I can merge your PR:
- [ ] Run pylint on miscserverinfo.py (and any other source file you may add). You'll see a few issues that should be a quick fix
- [ ] Add a unit test under irods/test/ that exercises the code in miscsvrinfo.py. See sample coverage figures [here](https://jenkins.irods.org/view/3.%20Client%20Verification/job/test-python-client-4.1.10-ub14/20/cobertura/_default_/)
- [ ] Squash your commits into one

**Comment by bascibaran** [comment]
I have refactored the code for PEP8 compliance and closer behavior to imiscsvrinfo. Instead of an uptime attribute, the object now has a serverBootTime attribute that returns in seconds since the beginning of the epoch, the boot time of the server. However, uptime is still computed and displayed in the string representation of the object.  I have also written an associated unit test miscsvrinfo_test.py which necessitated the addition of an extra name definition in config.py. I have squashed my commits into commit 54dbbdc.

**Comment by adetorcy** [comment]
May I close this pull request due to inactivity?

If you are still interested in adding this functionality it might be easier to move your commits to another branch and bring your master branch up to date, rather than rebasing and resolving conflicts since things have moved quite a bit lately. Just a thought.

**Comment by bascibaran** [comment]
Sounds good.

**Pull request closed without merging**
