### PR TITLE
fix the PAM authentication with env json file.

### PR DESCRIPTION
**Pull request by gscteam**
Fix issue #156

### CODE REVIEW

**Comment by trel** [comment]
Thanks for this!

We can get it merged with a test that demonstrates/exercises this codepath.

**Comment by gscteam** [comment]
Hi, 

I am not sure what is needed , I did not find any code in test/ that test the different session. The helper has a make_session that does not test the PAM session. If you mean 'how to trigger the bug', i think it is in the associated issue.

**Comment by MaximeVdB** [comment]
Hi! I just wanted to confirm that this also works on our systems, and that we would like it to be included in an official release. If I could help out in some way, let me know.

**Comment by trel** [comment]
This is being put into a test harness now - fix confirmed - will be included in the next release.

**Comment by trel** [comment]
incorporated into #206 - keeping attribution.

**Pull request closed without merging**
