### PR TITLE
calculate common vault dir for unicode query tests

### PR DESCRIPTION
**Pull request by d-w-moore**
Two tests querying for unicode object names got minor changes / refactor.
The tests were failing at bench, but passing in CI. With this commit, they are green in both places.

### CODE REVIEW

**Comment by trel** [comment]
let's get an issue number associated with it - and i think we're good to go.

**Comment by d-w-moore** [comment]
This also seems ready for merge.  But will submit for review if that is preferable !

**Comment by trel** [comment]
good good - please # it.

**Comment by trel** [comment]
you missed.

**Pull request merged**
