### PR TITLE
Allow ADMIN_KW in Python metadata API requests

### PR DESCRIPTION
**Pull request by d-w-moore**

### CODE REVIEW

**Comment by d-w-moore** [comment]
contingent on https://github.com/irods/python-irodsclient/pull/363

**Comment by d-w-moore** [comment]
That said, I am testing it now for inclusion in release ` 1.1.4` .

**Comment by trel** [comment]
if it's good - please squash and we'll eyeball it one more time before #.

**Comment by trel** [comment]
looks good to me - please # em

**Comment by d-w-moore** [comment]
ok, ready for merge. Took the liberty of changing kw -> kw_ to avoid shadowing a global. Re-tested as well. (Codacy had flagged it; otherwise the codacy concerns seemed too minor to worry about.)

**Review by alanking — APPROVED** [review]

**Pull request merged**
