### PR TITLE
Disallow PAM auth cleartext passwords

### PR DESCRIPTION
**Pull request by d-w-moore**
tested on top of #191  using this [test harness](https://github.com/d-w-moore/misc/blob/prc_pam_test/harness/pam_test.sh)

### CODE REVIEW

**Comment by trel** [comment]
looks good - let's get the test harness into this repository in a clean way - atop this PR.

**Comment by trel** [comment]
seems good - please squash to taste and add issue numbers.

**Comment by d-w-moore** [comment]
Do we want this squashed and merged independent of the integrated test harness for (PAM/irods - env/args - /SSH=no/yes) , or is it better to wait knowing the tests are coming close on its heels ?

**Comment by trel** [comment]
let's squash for now - we've got the harness you developed linked - and it will get integrated soon enough.

**Pull request merged**
