### PR TITLE
[#615] reformat all Python source using black 24.10.0

### PR DESCRIPTION
**Pull request by d-w-moore**
Ran black formatter v24.10.0 on Python 3:12.  Running test suite on Python 3.8 and Python 3.6

### CODE REVIEW

**Review by alanking — COMMENTED** [review]
I'm guessing that this is in draft while we await test results, or do you expect more changes regardless?

**Comment by trel** [comment]
i expect no changes.   just awaiting the 'all clear'.

**Comment by d-w-moore** [comment]
Tests all pass. With black formatting, we are good for release of v3.0.0 ....

**Review by alanking — APPROVED** [review]
Eyeball inspection looks good. Tests are passing. Please take out of draft and # it.

**Comment by d-w-moore** [comment]
> Eyeball inspection looks good. Tests are passing. Please take out of draft and # it.

Done,and done.

**Pull request merged**
